### ISSUE TITLE
How it will connect to logging-es in aggregate logging

### ISSUE THREAD

**Issue by aaryabhatt** [garethahealy/elastalert-on-ocp#1]
Hi
I am searching for how to connect elastalert to openshift origin with aggregate logging elasticsearch. I come to your repo. I would like to know. how it will connect to elasticsearch. I would be great help if you could give detailed info. I can connect to els with curl with -k option with elastic secret in openshift logging project, but can't connect through elastalert-create-index command. 

--
Thanks
Amit

**Comment by garethahealy** [comment]
@aaryabhatt ; when i created this repo, it wasn't possible to provide elastalert with the keys for mutual auth - as required by openshift logging. A PR has now been merged which makes this possible, but obviously, i've not had time to update this repo.

**Comment by aaryabhatt** [comment]
can you guide me, where I can check his info, or how can i implement this, It will be very helpful

**Comment by garethahealy** [comment]
See this PR:
- https://github.com/Yelp/elastalert/pull/1289/files

Hopefully should explain what options you need to set.

**Comment by aaryabhatt** [comment]
thanks for your quick response.

**Comment by yeplaa** [comment]
Hello, 
As aaryabhatt, i'm trying connect to aggregate logging elasticsearch from ElastAlert but it's KO.  Elasticsearch is exposed by oauth2. The PR evokes the SSL configuration (client_cert, ca_certs...) but  the oauth2 requires the X-Proxy-Remote-User and the token in the header of the requests. 
It works for you? 
Thank's for your help

Loïc

**Comment by garethahealy** [comment]
@yeplaa ; i've not used it with OAuth2, so dont know. You'd need to check the docs.
